### PR TITLE
Moved the Documentation into a new folder to centrally manage the Documentation and it's up keep. 

### PR DESCRIPTION
**Pull request by CSDUMMI**
In this #96 issue I raised, I have specified, how the spread out documentation
is a problem for developers, trying to find a specific feature of OrbitDB.

I thus started here to compile the Documentation into a single Folder with only very few  files,
such that people can easily search them and later convert this into a cook book for OrbitDB.

### CODE REVIEW

**Comment by CSDUMMI** [comment]
@aphelionz would you merge this or do you need anything more?

The Project isn't finished yet, but if we wait too long, the documentations will get out of sync.

**Comment by tabcat** [comment]
I dont like that this copies all the stores README files into this repos docs/ folder. First it just makes more documents needed to be maintained and updated. 
If your plan is to move, instead of copy, just the API documentation it makes more sense but im still not a fan because the API documentation IMO should be a part the repo it belongs to. 
Generating API documents with JSDoc  would be more appealing in the long run and would be easy to automate inside the main repo and/or generate a website from it.

**Comment by aphelionz** [comment]
Big fan of a nice slick website with everything on it

**Comment by CSDUMMI** [comment]
> Generating API documents with JSDoc would be more appealing in the long run and would be easy to automate inside the main repo and/or generate a website from it.
@tabcat I would surely support using JSDoc instead.


How do you plan to go about this?

**Comment by aphelionz** [comment]
side note: JSDoc is great but it feels _so_ outdated. I spent days looking for something similar but I couldnt find anything. I'd love to have an alternative if anybody has a good one. Something like `rustdoc` would be amazing if we could run functional tests on the code snippets in the docs / examples

**Comment by CSDUMMI** [comment]
What do you think of [sphinx-js](https://github.com/mozilla/sphinx-js). It appears to be based on JSDoc and extend it.

**Comment by aphelionz** [comment]
yeah sphinx looks compelling

**Comment by CSDUMMI** [comment]
I'll try to get some info on it. But if we use it, we'll need Documentation in the source code. 
I would start with the [orbit-db-store](https://github.com/orbitdb/orbit-db-store) package.

**Comment by aphelionz** [comment]
I love this idea @CSDUMMI, do you want to make `orbit-db-store` the examplar then, and we can look into publishing options?

**Comment by CSDUMMI** [comment]
Yes. I would like to do that. But perhaps it is better to start with the [orbit-db](https://github.com/orbitdb/orbit-db) repository, since that is the one, that'll be most easily documented for examplar purposes.

**Comment by CSDUMMI** [comment]
I already started doing using sphinx-js on my orbit-db repository fork and I will try to create PR within the next weeks. https://github.com/CSDUMMI/orbit-db/tree/master

**Comment by CSDUMMI** [comment]
I raised an issue on the repository.
I would like to move the discussion there.

**Comment by aphelionz** [comment]
>  orbit-db repository, since that is the one, that'll be most easily documented for examplar purposes.

I would say that's the most difficult since it contains every single concept in OrbitDB (keystore, cache, heads exchange, pubsub, IPFS dag, etc etc), but if you feel differently, go for it!

**Comment by CSDUMMI** [comment]
> > orbit-db repository, since that is the one, that'll be most easily documented for examplar purposes.
> 
> I would say that's the most difficult since it contains every single concept in OrbitDB (keystore, cache, heads exchange, pubsub, IPFS dag, etc etc), but if you feel differently, go for it!

I don't need to document everything, just enough to get an example.

**Pull request closed without merging**
