### PR TITLE
Add an FAQ

### PR DESCRIPTION
**Pull request by RichardLitt**
This is an initial attempt to get an FAQ up and running. I do not think that this is a permanent solution, but it should help us get the ball rolling on having an FAQ at all. I started this as suggested by @mistakia [here](https://github.com/orbitdb/orbit-db/issues/440#issuecomment-416347226).

### CODE REVIEW

**Comment by RichardLitt** [comment]
Hmm. I don't want to merge this if no one else has noticed it. @haadcode, thoughts?

**Comment by haadcode** [comment]
@RichardLitt sorry, this fell through the cracks in my inbox. Looks good to me to merge! 👍Gotta start somewhere 😄

**Comment by haadcode** [comment]
And thank you for taking the initiative to start it, this will be useful for many! ❤️

**Comment by RichardLitt** [comment]
No worries! Let's hope. :)

**Pull request merged**
